# Model hyperparameters and thresholds

classifier:
  model_type: "LogisticRegression"
  params:
    class_weight: "balanced"
    C: 0.1
    max_iter: 1000
    solver: "liblinear"

  rules:
    # Rules based on core dataset features
    distance_from_home_threshold: 100
    distance_from_last_transaction_threshold: 50
    ratio_to_median_purchase_price_threshold: 3.0
    payment_method_rules:
      no_chip_no_pin: true
      online_order_flag: true
    new_retailer_flag: true

anomaly:
  model_type: "IsolationForest"
  params:
    n_estimators: 100
    contamination: 0.01
    random_state: 42
    max_samples: "auto"

  thresholds:
    # Thresholds based on evaluation of core dataset features
    critical_threshold: -0.1
    high_threshold: 0.05
    normal_threshold: 0.1
    adjustment_rate: 0.1

  feature_importance:
    distance_features_weight: 0.4
    payment_method_weight: 0.4
    purchase_pattern_weight: 0.2

mediator:
  # Adjusted weights based on model evaluation
  classifier_weight: 0.8  # Increased due to better performance
  anomaly_weight: 0.2     # Decreased due to lower performance
  confidence_threshold: 0.9
  block_threshold: 0.8
  review_threshold: 0.5

  # Core feature importance in decision making
  feature_weights:
    distance_features: 0.3
    payment_method: 0.4
    purchase_pattern: 0.3

memory:
  context_buffer_size: 1000
  fraud_pattern_retention: 90
  # Removed user_history_days as we're not using user profiles