classifier:
  model_type: LogisticRegression
  params:
    class_weight: balanced
    C: 0.5
    max_iter: 1000
    solver: liblinear
  rules:
    distance_rules:
      high_distance_from_home: 100
      high_distance_from_last_transaction: 50
    transaction_pattern_rules:
      high_ratio_to_median_threshold: 3.0
      new_retailer_flag: true
    payment_method_rules:
      no_chip: true
      no_pin: true
      online_order: true
anomaly:
  model_type: IsolationForest
  params:
    n_estimators: 100
    contamination: 0.01
    random_state: 42
    max_samples: auto
  thresholds:
    critical_threshold: -0.1
    high_threshold: 0.05
    normal_threshold: 0.1
    adjustment_rate: 0.1
  feature_importance:
    distance_from_home_weight: 0.2
    distance_from_last_transaction_weight: 0.2
    ratio_to_median_purchase_price_weight: 0.2
    repeat_retailer_weight: 0.1
    used_chip_weight: 0.1
    used_pin_number_weight: 0.1
    online_order_weight: 0.1
mediator:
  classifier_weight: 0.8
  anomaly_weight: 0.2
  confidence_threshold: 0.9
  block_threshold: 0.8
  review_threshold: 0.5
  feature_weights:
    distance_features: 0.4
    payment_method: 0.3
    purchase_pattern: 0.3
memory:
  context_buffer_size: 1000
  fraud_pattern_retention: 90
