# Model hyperparameters and thresholds

classifier:
  model_type: "LogisticRegression"
  params:
    class_weight: "balanced"
    C: 0.1
    max_iter: 1000
    solver: "liblinear"
  
  rules:
    max_hourly_transactions: 5
    amount_deviation_multiplier: 3
    max_daily_amount: 10000
    suspicious_countries: ["XX", "YY", "ZZ"]

anomaly:
  model_type: "IsolationForest"
  params:
    n_estimators: 100
    contamination: 0.01
    random_state: 42
    max_samples: "auto"
  
  thresholds:
    critical_threshold: -0.7
    high_threshold: -0.4
    normal_threshold: -0.2
    adjustment_rate: 0.1

mediator:
  classifier_weight: 0.7
  anomaly_weight: 0.3
  confidence_threshold: 0.9
  block_threshold: 0.8
  review_threshold: 0.5

memory:
  context_buffer_size: 1000
  user_history_days: 30
  fraud_pattern_retention: 90